package uk.ac.gla.cvr.hackathon2016.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Analysis was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Analysis extends CayenneDataObject {

    public static final String ANALYSIS_DATE_PROPERTY = "analysisDate";
    public static final String DENOVO_OPTIONS_PROPERTY = "denovoOptions";
    public static final String DENOVO_PROGRAM_PROPERTY = "denovoProgram";
    public static final String KNONW_GENOMES_IN_THE_SAMPLE_PROPERTY = "knonwGenomesInTheSample";
    public static final String NOTES_PROPERTY = "notes";
    public static final String NR_VERSION_PROPERTY = "nrVersion";
    public static final String NT_VERSTION_PROPERTY = "ntVerstion";
    public static final String PROG_AND_OPTIONSFOR_NR_SEARCH_PROPERTY = "progAndOptionsforNrSearch";
    public static final String PROG_AND_OPTIONSFOR_NT_SEARCH_PROPERTY = "progAndOptionsforNtSearch";
    public static final String RESEARCHER_PROPERTY = "researcher";
    public static final String SEQ_ID_PROPERTY = "seqID";

    public static final String SEQ_ID_PK_COLUMN = "seqID";

    public void setAnalysisDate(Date analysisDate) {
        writeProperty(ANALYSIS_DATE_PROPERTY, analysisDate);
    }
    public Date getAnalysisDate() {
        return (Date)readProperty(ANALYSIS_DATE_PROPERTY);
    }

    public void setDenovoOptions(String denovoOptions) {
        writeProperty(DENOVO_OPTIONS_PROPERTY, denovoOptions);
    }
    public String getDenovoOptions() {
        return (String)readProperty(DENOVO_OPTIONS_PROPERTY);
    }

    public void setDenovoProgram(String denovoProgram) {
        writeProperty(DENOVO_PROGRAM_PROPERTY, denovoProgram);
    }
    public String getDenovoProgram() {
        return (String)readProperty(DENOVO_PROGRAM_PROPERTY);
    }

    public void setKnonwGenomesInTheSample(String knonwGenomesInTheSample) {
        writeProperty(KNONW_GENOMES_IN_THE_SAMPLE_PROPERTY, knonwGenomesInTheSample);
    }
    public String getKnonwGenomesInTheSample() {
        return (String)readProperty(KNONW_GENOMES_IN_THE_SAMPLE_PROPERTY);
    }

    public void setNotes(String notes) {
        writeProperty(NOTES_PROPERTY, notes);
    }
    public String getNotes() {
        return (String)readProperty(NOTES_PROPERTY);
    }

    public void setNrVersion(String nrVersion) {
        writeProperty(NR_VERSION_PROPERTY, nrVersion);
    }
    public String getNrVersion() {
        return (String)readProperty(NR_VERSION_PROPERTY);
    }

    public void setNtVerstion(String ntVerstion) {
        writeProperty(NT_VERSTION_PROPERTY, ntVerstion);
    }
    public String getNtVerstion() {
        return (String)readProperty(NT_VERSTION_PROPERTY);
    }

    public void setProgAndOptionsforNrSearch(String progAndOptionsforNrSearch) {
        writeProperty(PROG_AND_OPTIONSFOR_NR_SEARCH_PROPERTY, progAndOptionsforNrSearch);
    }
    public String getProgAndOptionsforNrSearch() {
        return (String)readProperty(PROG_AND_OPTIONSFOR_NR_SEARCH_PROPERTY);
    }

    public void setProgAndOptionsforNtSearch(String progAndOptionsforNtSearch) {
        writeProperty(PROG_AND_OPTIONSFOR_NT_SEARCH_PROPERTY, progAndOptionsforNtSearch);
    }
    public String getProgAndOptionsforNtSearch() {
        return (String)readProperty(PROG_AND_OPTIONSFOR_NT_SEARCH_PROPERTY);
    }

    public void setResearcher(String researcher) {
        writeProperty(RESEARCHER_PROPERTY, researcher);
    }
    public String getResearcher() {
        return (String)readProperty(RESEARCHER_PROPERTY);
    }

    public void setSeqID(String seqID) {
        writeProperty(SEQ_ID_PROPERTY, seqID);
    }
    public String getSeqID() {
        return (String)readProperty(SEQ_ID_PROPERTY);
    }

}
