package uk.ac.gla.cvr.hackathon2016.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _KnownDark was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _KnownDark extends CayenneDataObject {

    public static final String ALN_LENGTH_PROPERTY = "alnLength";
    public static final String BIT_SCORE_PROPERTY = "bitScore";
    public static final String CONTIG_END_PROPERTY = "contigEnd";
    public static final String CONTIG_ID_PROPERTY = "contigID";
    public static final String CONTIG_START_PROPERTY = "contigStart";
    public static final String E_VAL_PROPERTY = "eVal";
    public static final String GAP_OPEN_COUNT_PROPERTY = "gapOpenCount";
    public static final String MISMATCH_COUNT_PROPERTY = "mismatchCount";
    public static final String PERC_IDENTITY_PROPERTY = "percIdentity";
    public static final String QUERY_END_PROPERTY = "queryEnd";
    public static final String QUERY_ID_PROPERTY = "queryID";
    public static final String QUERY_START_PROPERTY = "queryStart";

    public static final String QUERY_ID_PK_COLUMN = "queryID";

    public void setAlnLength(Integer alnLength) {
        writeProperty(ALN_LENGTH_PROPERTY, alnLength);
    }
    public Integer getAlnLength() {
        return (Integer)readProperty(ALN_LENGTH_PROPERTY);
    }

    public void setBitScore(Float bitScore) {
        writeProperty(BIT_SCORE_PROPERTY, bitScore);
    }
    public Float getBitScore() {
        return (Float)readProperty(BIT_SCORE_PROPERTY);
    }

    public void setContigEnd(Integer contigEnd) {
        writeProperty(CONTIG_END_PROPERTY, contigEnd);
    }
    public Integer getContigEnd() {
        return (Integer)readProperty(CONTIG_END_PROPERTY);
    }

    public void setContigID(String contigID) {
        writeProperty(CONTIG_ID_PROPERTY, contigID);
    }
    public String getContigID() {
        return (String)readProperty(CONTIG_ID_PROPERTY);
    }

    public void setContigStart(Integer contigStart) {
        writeProperty(CONTIG_START_PROPERTY, contigStart);
    }
    public Integer getContigStart() {
        return (Integer)readProperty(CONTIG_START_PROPERTY);
    }

    public void setEVal(Float eVal) {
        writeProperty(E_VAL_PROPERTY, eVal);
    }
    public Float getEVal() {
        return (Float)readProperty(E_VAL_PROPERTY);
    }

    public void setGapOpenCount(Integer gapOpenCount) {
        writeProperty(GAP_OPEN_COUNT_PROPERTY, gapOpenCount);
    }
    public Integer getGapOpenCount() {
        return (Integer)readProperty(GAP_OPEN_COUNT_PROPERTY);
    }

    public void setMismatchCount(Integer mismatchCount) {
        writeProperty(MISMATCH_COUNT_PROPERTY, mismatchCount);
    }
    public Integer getMismatchCount() {
        return (Integer)readProperty(MISMATCH_COUNT_PROPERTY);
    }

    public void setPercIdentity(Float percIdentity) {
        writeProperty(PERC_IDENTITY_PROPERTY, percIdentity);
    }
    public Float getPercIdentity() {
        return (Float)readProperty(PERC_IDENTITY_PROPERTY);
    }

    public void setQueryEnd(Integer queryEnd) {
        writeProperty(QUERY_END_PROPERTY, queryEnd);
    }
    public Integer getQueryEnd() {
        return (Integer)readProperty(QUERY_END_PROPERTY);
    }

    public void setQueryID(String queryID) {
        writeProperty(QUERY_ID_PROPERTY, queryID);
    }
    public String getQueryID() {
        return (String)readProperty(QUERY_ID_PROPERTY);
    }

    public void setQueryStart(Integer queryStart) {
        writeProperty(QUERY_START_PROPERTY, queryStart);
    }
    public Integer getQueryStart() {
        return (Integer)readProperty(QUERY_START_PROPERTY);
    }

}
