package uk.ac.gla.cvr.hackathon2016.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Orf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Orf extends CayenneDataObject {

    public static final String CONTIG_ID_PROPERTY = "contigID";
    public static final String DIR_PROPERTY = "dir";
    public static final String LEN_PROPERTY = "len";
    public static final String ORF_ID_PROPERTY = "orfID";
    public static final String SEQ_PROPERTY = "seq";
    public static final String START_PROPERTY = "start";
    public static final String STOP_PROPERTY = "stop";
    public static final String UNIQ_ID_PROPERTY = "uniqID";

    public static final String UNIQ_ID_PK_COLUMN = "uniqID";

    public void setContigID(String contigID) {
        writeProperty(CONTIG_ID_PROPERTY, contigID);
    }
    public String getContigID() {
        return (String)readProperty(CONTIG_ID_PROPERTY);
    }

    public void setDir(String dir) {
        writeProperty(DIR_PROPERTY, dir);
    }
    public String getDir() {
        return (String)readProperty(DIR_PROPERTY);
    }

    public void setLen(Integer len) {
        writeProperty(LEN_PROPERTY, len);
    }
    public Integer getLen() {
        return (Integer)readProperty(LEN_PROPERTY);
    }

    public void setOrfID(String orfID) {
        writeProperty(ORF_ID_PROPERTY, orfID);
    }
    public String getOrfID() {
        return (String)readProperty(ORF_ID_PROPERTY);
    }

    public void setSeq(String seq) {
        writeProperty(SEQ_PROPERTY, seq);
    }
    public String getSeq() {
        return (String)readProperty(SEQ_PROPERTY);
    }

    public void setStart(Integer start) {
        writeProperty(START_PROPERTY, start);
    }
    public Integer getStart() {
        return (Integer)readProperty(START_PROPERTY);
    }

    public void setStop(Integer stop) {
        writeProperty(STOP_PROPERTY, stop);
    }
    public Integer getStop() {
        return (Integer)readProperty(STOP_PROPERTY);
    }

    public void setUniqID(String uniqID) {
        writeProperty(UNIQ_ID_PROPERTY, uniqID);
    }
    public String getUniqID() {
        return (String)readProperty(UNIQ_ID_PROPERTY);
    }

}
