package uk.ac.gla.cvr.hackathon2016.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Sample was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sample extends CayenneDataObject {

    public static final String COLLECTION_DATE_PROPERTY = "collectionDate";
    public static final String HOST_PROPERTY = "host";
    public static final String METAGENOMICS_PROPERTY = "metagenomics";
    public static final String OWNER_PROPERTY = "owner";
    public static final String SMP_ID_PROPERTY = "smpID";
    public static final String SOURCE_PROPERTY = "source";

    public static final String SMP_ID_PK_COLUMN = "smpID";

    public void setCollectionDate(Date collectionDate) {
        writeProperty(COLLECTION_DATE_PROPERTY, collectionDate);
    }
    public Date getCollectionDate() {
        return (Date)readProperty(COLLECTION_DATE_PROPERTY);
    }

    public void setHost(String host) {
        writeProperty(HOST_PROPERTY, host);
    }
    public String getHost() {
        return (String)readProperty(HOST_PROPERTY);
    }

    public void setMetagenomics(Short metagenomics) {
        writeProperty(METAGENOMICS_PROPERTY, metagenomics);
    }
    public Short getMetagenomics() {
        return (Short)readProperty(METAGENOMICS_PROPERTY);
    }

    public void setOwner(String owner) {
        writeProperty(OWNER_PROPERTY, owner);
    }
    public String getOwner() {
        return (String)readProperty(OWNER_PROPERTY);
    }

    public void setSmpID(Integer smpID) {
        writeProperty(SMP_ID_PROPERTY, smpID);
    }
    public Integer getSmpID() {
        return (Integer)readProperty(SMP_ID_PROPERTY);
    }

    public void setSource(String source) {
        writeProperty(SOURCE_PROPERTY, source);
    }
    public String getSource() {
        return (String)readProperty(SOURCE_PROPERTY);
    }

}
